<?php
/**
 * @category     Inchoo
 * @package     Inchoo Featured Products
 * @author        Domagoj Potkoc, Inchoo Team <web@inchoo.net>
 * @modified    Mladen Lotar <mladen.lotar@surgeworks.com>, Vedran Subotic <vedran.subotic@surgeworks.com>
 */
?>
<?php $image_size = (int) Mage::getStoreConfig("featuredproducts/cmspage/max_image_dimension") ?>
<?php if (($_products = $this->getProductCollection()) && $_products->getSize()): ?>
    <div class="featuredProducts">
    <h2><?php echo $this->__($this->getBlockLabel()) ?></h2>
    <ul class="products-grid products-grid--max-6-col first last odd">


            <?php
            $i = 0;
            $row = 0;
            foreach ($_products->getItems() as $_product):
                ?>


                    <li class="item last">
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>" class="product-image">
                            <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($image_size, $image_size) ?>" alt="<?php echo $this->htmlEscape($_product->getName()) ?>">
                        </a>
                        <div class="product-info">
                            <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><?php echo $this->htmlEscape($_product->getName()) ?></a></h2>
                            <div class="actions">
                                <?php if (Mage::getStoreConfig('featuredproducts/general/price_visible')): ?>

                                    <?php echo $this->getPriceHtml($_product, true, '-new') ?>

                                    <?php if ($_product->isSaleable()){
                                        <button type="button" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                                <?php endif; ?>

                            </div>
                        </div>
                    </li>



                    <?php $i++;
                    if ($i == $this->getItemsPerRow()):
                        ?>
                    <?php $i = 0; ?>
                    </tr>
        <?php endif; ?>
    <?php endforeach; ?>

    </ul>
    </div>
<?php endif; ?>
